### PR TITLE
The Great Venue Refactor (I)

### PR DESCRIPTION
**Pull request by seveibar**
Making this a PR so it's easier to find.

Special thanks to Kiana picking up the slack recently and fixing the part of the client I was stuck on :)

### CODE REVIEW

**Comment by kmcnellis** [comment]
Current problems: Google Maps and tests

**Comment by seveibar** [comment]
selection_002

I think you need to commit eventinfo?

**Comment by kmcnellis** [comment]
It is there https://github.com/rcos/venue/tree/flowtype/client/app/eventInfo

**Comment by seveibar** [comment]
it looks like the "I" is capitalized

**Comment by seveibar** [comment]
fixing now

**Comment by seveibar** [comment]
Without doing a full runthrough it looks pretty good- we are in desperate need of client side tests hahaha

**Comment by seveibar** [comment]
One issue:

**Comment by seveibar** [comment]
selection_003

:penguin:

**Comment by kmcnellis** [comment]
Thats the MDL styling thing I was talking about before. I know we fixed it last time, just have to take a closer look

**Comment by seveibar** [comment]
@kmcnellis there's an issue with geojson validation from the seed (check the travis build) I don't see it on my system :/

**Comment by seveibar** [comment]
also note that travis thinks the test is passing when it is clearly failing

**Comment by kmcnellis** [comment]
I need more specifics. I don't know what test you are referring to

**Comment by seveibar** [comment]
@kmcnellis ugh why is travis passing with failing builds? ill investigate ASAP

**Comment by seveibar** [comment]
fetch api is the only remaining failing thing

**Pull request merged**
