### PR TITLE
Display additional info on event page

### PR DESCRIPTION
**Pull request by kmcnellis**
Working towards #175

### CODE REVIEW

**Comment by samanthajlee2** [comment]
looks good (when logged in) but when I log out, this is left on the page...

mar15_232227

**Comment by kmcnellis** [comment]
I don't believe I changed anything with regards to signed out behavior - Do you think the page should be visible to non-logged in users or inaccessible to them?

**Comment by samanthajlee2** [comment]
Currently if a user is on a page like courses that is visible to non-logged in users and that user logs out, the page stays there, but if a user is on a page like upload, or create event, or dashboard, and the logs out, the default seems to be go back to the login page (there are a few exceptions, those are now filed as bugs).

I think this specific page should be inaccessible to them, if someone isn't logged in, they shouldn't need to see events. If a user is not logged in, they only need to see courses so they can enroll, does that make sense?

**Comment by kmcnellis** [comment]
I will address the page visibility as part of a different issue & pr.

**Comment by kmcnellis** [comment]
Relevant issues: #188, #187, #191

**Comment by kmcnellis** [comment]
The logout issue is addressed in #192

**Pull request merged**
