### PR TITLE
Image url formatted like files

### LINKED ISSUE #357: Image URLs should be formatted like files
This is a P1 because it blocks #272 

Image requests currently use GET parameters. They should just be like normal static files on a server.

Example:
`http://127.0.0.1:9000/api/eventinfos/image?name=kitten1-1469573189386.jpeg`

What it should be:
`http://127.0.0.1:9000/api/eventinfos/image/kitten1-1469573189386.jpeg`

### PR DESCRIPTION
**Pull request by kmcnellis**
Fixes #357

### CODE REVIEW

**Comment by seveibar** [comment]
wow speedy, I'll review in a sec

**Comment by seveibar** [comment]
This does solve the nginx problem, but this is not "file-like" because an image is both a directory AND a file (unless I'm misunderstanding).

The two URLs are valid.

`/image/:name`

`/image/:name/:size`

The seed also needs to be modified to reflect the new image urls (I think).

**Comment by seveibar** [comment]
I uploaded to an event and got the following URL in my submission response...

`http://127.0.0.1:9000/api/submissions/image?imgPath=./data/eventImages/000000000000000000000004/000000000000000000001000/submission1.jpg`

**Comment by kmcnellis** [comment]
That link must have been left over from something else. I'll take a look. 

What do you mean by "this is not "file-like" because an image is both a directory AND a file"?
The second url maps to the size-changed version of the file. 
I'm not really sure what you are asking

**Comment by seveibar** [comment]
Yes, but in a traditional file system a file is not also a directory.

Consider the following urls
`/image/dog.png`
`/image/dog.png/small.png`

In this case, `dog.png` is both a file and directory.

**Comment by kmcnellis** [comment]
You mean that the subfolders in the directory path should not have file extensions? (files are never directories).

Is what you want that each url can be directly mapped to the file system?

**Comment by kmcnellis** [comment]
I can make the name the last part of each url

**Comment by seveibar** [comment]
Yea that's perfect, and yea the URL needs to in some way indicate a file location... is that tricky?

**Comment by kmcnellis** [comment]
The only tricky part is specifying the small/large pictures. They are saved with -preview or -large appended, but for ease of use, the original api allowed you to specify ?size=preview. I can just remove that part (as we never used it anywhere) and require the client to specify it on its own. Or it can be in a seperate directory (I'm thinking near the top level)

**Comment by seveibar** [comment]
IMO the cleanest way is for each image to have it's own directory

i.e. the directory contains the preview, large, small etc.

**Comment by kmcnellis** [comment]
What do you mean by that?

**Comment by seveibar** [comment]
Oh I misunderstood the problem, I agree with your approach

**Comment by seveibar** [comment]
I don't think that build error is your fault, im investigating now.

**Comment by seveibar** [comment]
mongodb doesn't seem to be starting up- I'm not sure why it isn't (maybe something happened in the merge?)

**Comment by seveibar** [comment]
I like the seed changes

**Comment by seveibar** [comment]
this is sweet

**Comment by kmcnellis** [comment]
What was the mongo issue?

**Comment by seveibar** [comment]
There was a change a while ago that made it so mongodb didn't run in the venue container by default- which is a docker convention.

**Comment by seveibar** [comment]
The test failed b/c it expected mongodb

**Pull request merged**
