### PR TITLE
new upload process with event selection

### PR DESCRIPTION
**Pull request by seveibar**
Allows linking to upload form for events.

### CODE REVIEW

**Comment by samanthajlee2** [comment]
@seveibar you might have accidentally broken the events page

**Comment by seveibar** [comment]
Hey @samanthajlee2 I pushed the fix, the automatic merge process would have fixed this b/c this was created before joey's PR was merged, but a good catch regardless (probably best practice)

**Comment by samanthajlee2** [comment]
@seveibar gotcha that makes sense. I didn't notice that this branch was created before joey's PR was merged.

In the future, we probably don't have to "double" merge so to say and let git handle the merge? (less work for you sort of thing)

**Comment by samanthajlee2** [comment]
Consider error messages if unable to upload.

For example, if location is not shared. (Currently nothing happens when the submit button is clicked if location is not shared.)

@seveibar maybe this should be a separate issue dealt with later since we want to focus on the instructor page more?

**Comment by seveibar** [comment]
yea i would file a separate issue for that

**Pull request merged**
