### PR TITLE
Frontend routes

### PR DESCRIPTION
**Pull request by seveibar**
This sets up a bunch of Frontend routes so that we only need to add content.

The generator was used extensively, here's the directory structure that was created within `client/app`...

```
courses
├── courses.controller.js
├── courses.controller.spec.js
├── courses.html
├── courses.js
└── courses.less
instructor
├── instructor.directive.js
├── instructor.directive.spec.js
├── instructor.html
├── instructor.less
└── signup
    ├── signup.controller.js
    ├── signup.controller.spec.js
    ├── signup.html
    ├── signup.js
    └── signup.less
student
├── dashboard
│   ├── dashboard.controller.js
│   ├── dashboard.controller.spec.js
│   ├── dashboard.html
│   ├── dashboard.js
│   └── dashboard.less
├── profile
│   ├── profile.controller.js
│   ├── profile.controller.spec.js
│   ├── profile.html
│   ├── profile.js
│   └── profile.less
├── signup
│   ├── signup.controller.js
│   ├── signup.controller.spec.js
│   ├── signup.html
│   ├── signup.js
│   └── signup.less
├── student.directive.js
├── student.directive.spec.js
├── student.html
├── student.less
└── upload
    ├── upload.controller.js
    ├── upload.controller.spec.js
    ├── upload.html
    ├── upload.js
    └── upload.less
```

You can also view them as the execution of the following lines of code (then configured)...

``` bash
 yo angular-fullstack:directive instructor
 yo angular-fullstack:directive student
 yo angular-fullstack:route courses
 yo angular-fullstack:route profile # student/:id/profile
 yo angular-fullstack:route upload # student/upload
 yo angular-fullstack:route signup # student/signup
 yo angular-fullstack:route signup # instructor/signup
 yo angular-fullstack:route dashboard # student/dashboard
```

### CODE REVIEW

**Comment by kmcnellis** [comment]
What about login?

**Comment by kmcnellis** [comment]
And what is courses for?

**Comment by seveibar** [comment]
there's already a login route- it can probably be universal?

**Comment by seveibar** [comment]
courses is to view all public courses and search

**Pull request merged**
